ext_rpc_service_stub.lo: /home/zhangdi05/git_space/sofa-pbrpc/php/ext_rpc_service_stub.cc
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/zhangdi05/git_space/sofa-pbrpc/php $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/zhangdi05/git_space/sofa-pbrpc/php/ext_rpc_service_stub.cc -o ext_rpc_service_stub.lo 
ext_rpc_service_stub_impl.lo: /home/zhangdi05/git_space/sofa-pbrpc/php/ext_rpc_service_stub_impl.cc
	$(LIBTOOL) --mode=compile $(CXX)  -I. -I/home/zhangdi05/git_space/sofa-pbrpc/php $(COMMON_FLAGS) $(CXXFLAGS_CLEAN) $(EXTRA_CXXFLAGS)  -c /home/zhangdi05/git_space/sofa-pbrpc/php/ext_rpc_service_stub_impl.cc -o ext_rpc_service_stub_impl.lo 
$(phplibdir)/sofa_pbrpc.la: ./sofa_pbrpc.la
	$(LIBTOOL) --mode=install cp ./sofa_pbrpc.la $(phplibdir)

./sofa_pbrpc.la: $(shared_objects_sofa_pbrpc) $(SOFA_PBRPC_SHARED_DEPENDENCIES)
	$(LIBTOOL) --mode=link $(CC) $(COMMON_FLAGS) $(CFLAGS_CLEAN) $(EXTRA_CFLAGS) $(LDFLAGS) -o $@ -export-dynamic -avoid-version -prefer-pic -module -rpath $(phplibdir) $(EXTRA_LDFLAGS) $(shared_objects_sofa_pbrpc) $(SOFA_PBRPC_SHARED_LIBADD)

